### PR TITLE
Add pyproject.toml for Custom Node Registry

### PR DESCRIPTION
**Pull request by haohaocreates**
We are working with dr.lt.data and comfyanon to build a global registry for custom nodes (similar to PyPI). Eventually, the registry will be used as a backend for the UI-manager. All nodes go through a verification process before being published to users.

The main benefits are that authors can
- publish nodes by version and users can safely update nodes knowing ahead of time if their workflows will break or not
- automate testing against new commits in the comfy repo and existing workflows through our CI/CD dashboard

Action Required:

- [ ] Go to the [registry](https://registry.comfy.org). Login and create a publisher id (everything after the `@` sign on your registry profile). 
- [ ] Add the publisher id into the pyproject.toml file.
- [ ] Merge the separate Github Actions PR, then merge this PR.

If you want to publish the node manually, [install the cli](https://docs.comfy.org/comfy-cli/getting-started#install-cli) by running `pip install comfy-cli`, then run `comfy node publish`

Check out our [docs](https://docs.comfy.org/registry/overview#introduction) if you want to know more about the registry. Otherwise, feel free to message me on discord at haohao_81202 or join our [server](https://discord.com/invite/comfyorg) if you have any questions!

### CODE REVIEW

**Comment by haohaocreates** [comment]
hey @daniel-lewis-ab, wanted to send a small nudge and ask if you had any questions!

**Comment by daniel-lewis-ab** [comment]
:thinking:

I'm currently feeling a bit off/tired/down and taking a short break where I
can.  I'm about a week from selling my house and have been renovating, am
working more than full time with Salt, and doing this, and some other
things.  In all of those aspects, I am tired and waiting for something.

I'm going for a walk, and I'm hoping to face this in about a week or so.

**Comment by haohaocreates** [comment]
Hey man that sounds like a lot of things going on 🥺 - hope you can power
through 💪💪💪! Take your time!

Hope you rest up Daniel!

**Comment by daniel-lewis-ab** [comment]
Appreciate it.  I think everyone's got things, but there's a value in
honesty when you're around people who aren't hostile.  I hope you're doing
well too, and appreciate your contributions to the community.

**Comment by daniel-lewis-ab** [comment]
Okay, so I went to registry, created an API key, and the screen is empty and only lets me change my name when I got to "My Nodes".
image

**Comment by haohaocreates** [comment]
Hey Daniel!!

Lmk if you are still running into issues with name changing?

**Pull request merged**
